### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Zren** [Zren/PyQuassel#1]
QDataStream
- [ ] QDateTime ~~deserialization~~ / serialization
- [x] QTime ~~deserialization~~ / ~~serialization~~
- [x] Message.flags deserialization

LibQuassel
- Connection
  - [ ] SSL (Meh, should be run on same host)
  - [ ] Encryption (Meh, should be run on same host)
- [x] HeartBeat

PushBullet
- [x] Lighter weight python library using urllib.
- [ ] Current nick highlight (must currently manually specify a token to highlight which ignore's nicks with a `_` suffix when the target nick is taken).
- [ ] Don't spam messages
  - It currently it delete's the old push and sends a new one with the previous messages. Chrome on windows does not hide the old notification however, so I probably need to dismiss it first, then delete it.
- [x] Link to WebApp

WebApp
- [x] sendInput
- [ ] Decent UI
- [ ] Serialize a generated flask session SECRET_KEY and a user api key.
- [ ] Login form (rather than just an api key parameter => session variable linked with the pushbullet plugin).
